service: linear
runtime: python310 # or whichever python works for your app
entrypoint: gunicorn -b :$PORT app:app

# instance_class: F4
handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
